imports:
  - { resource: ./application.yaml }

services:
  YieldTracker.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: [ '@Shared.ConnectionManager' ]

  Shared.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/EventBus/InMemory/InMemorySyncEventBus
    arguments: []
